const images = [
  {
    id: 1,
    title: "Illidan Stormrage",
    src: "https://static.wikia.nocookie.net/wowpedia/images/2/2e/Illidan_Stormrage.jpg",
    alt: "Illidan Stormrage, le Seigneur des Brisés",
    isBoss: true,
    hint: "Le Seigneur des Brisés avec ses ailes démoniaques.",
  },
  {
    id: 2,
    title: "Goule nécrophage",
    src: "https://static.wikia.nocookie.net/wowpedia/images/5/5c/Ghoul.jpg",
    alt: "Goule nécrophage",
    isBoss: false,
    hint: "Un mort-vivant ordinaire qui rôde dans les cimetières.",
  },
  {
    id: 3,
    title: "Archimonde",
    src: "https://static.wikia.nocookie.net/wowpedia/images/4/4e/Archimonde.jpg",
    alt: "Archimonde, le Dévastateur",
    isBoss: true,
    hint: "Le puissant seigneur de la Légion Ardente.",
  },
  {
    id: 4,
    title: "Loup redoutable",
    src: "https://static.wikia.nocookie.net/wowpedia/images/3/3a/Dire_Wolf.jpg",
    alt: "Loup redoutable",
    isBoss: false,
    hint: "Un prédateur sauvage des forêts.",
  },
  {
    id: 5,
    title: "Deathwing",
    src: "https://static.wikia.nocookie.net/wowpedia/images/7/7a/Deathwing.jpg",
    alt: "Deathwing, l'Aile de la Mort",
    isBoss: true,
    hint: "L'ancien Aspect de la Terre, corrompu par le mal.",
  },
  {
    id: 6,
    title: "Orc guerrier",
    src: "https://static.wikia.nocookie.net/wowpedia/images/2/2c/Orc_warrior.jpg",
    alt: "Orc guerrier",
    isBoss: false,
    hint: "Un combattant orc typique.",
  },
  {
    id: 7,
    title: "Kil'jaeden",
    src: "https://static.wikia.nocookie.net/wowpedia/images/5/5e/Kil%27jaeden.jpg",
    alt: "Kil'jaeden, le Trompeur",
    isBoss: true,
    hint: "Le second en commandement de la Légion Ardente.",
  },
  {
    id: 8,
    title: "Araignée des cryptes",
    src: "https://static.wikia.nocookie.net/wowpedia/images/8/8b/Crypt_Spider.jpg",
    alt: "Araignée des cryptes",
    isBoss: false,
    hint: "Une créature rampante des donjons sombres.",
  },
  {
    id: 9,
    title: "Ragnaros",
    src: "https://static.wikia.nocookie.net/wowpedia/images/4/4b/Ragnaros.jpg",
    alt: "Ragnaros, Seigneur du Feu",
    isBoss: true,
    hint: "Le seigneur élémentaire du feu.",
  },
  {
    id: 10,
    title: "Golem de pierre",
    src: "https://static.wikia.nocookie.net/wowpedia/images/6/6e/Stone_Golem.jpg",
    alt: "Golem de pierre",
    isBoss: false,
    hint: "Une construction magique animée.",
  },
];

export default images;
