const images = [
  {
    id: 1,
    title: "Visage mystérieux 1",
    src: "https://picsum.photos/seed/boss1/900/600",
    alt: "Personnage mystérieux 1",
    isBoss: true,
    hint: "Regarde sa posture impressionnante.",
  },
  {
    id: 2,
    title: "Visage mystérieux 2",
    src: "https://picsum.photos/seed/rogue2/900/600",
    alt: "Personnage mystérieux 2",
    isBoss: false,
    hint: "Ce personnage a l'air plus discret.",
  },
  {
    id: 3,
    title: "Visage mystérieux 3",
    src: "https://picsum.photos/seed/warrior3/900/600",
    alt: "Personnage mystérieux 3",
    isBoss: true,
    hint: "Son regard est très intense.",
  },
  {
    id: 4,
    title: "Visage mystérieux 4",
    src: "https://picsum.photos/seed/adventurer4/900/600",
    alt: "Personnage mystérieux 4",
    isBoss: false,
    hint: "On dirait un aventurier ordinaire.",
  },
  {
    id: 5,
    title: "Visage mystérieux 5",
    src: "https://picsum.photos/seed/boss5/900/600",
    alt: "Personnage mystérieux 5",
    isBoss: true,
    hint: "Sa tenue est très imposante.",
  },
  {
    id: 6,
    title: "Visage mystérieux 6",
    src: "https://picsum.photos/seed/hunter6/900/600",
    alt: "Personnage mystérieux 6",
    isBoss: false,
    hint: "Il semble attaquer avec méthode.",
  },
  {
    id: 7,
    title: "Visage mystérieux 7",
    src: "https://picsum.photos/seed/boss7/900/600",
    alt: "Personnage mystérieux 7",
    isBoss: true,
    hint: "Il a l'air plus dangereux que les autres.",
  },
  {
    id: 8,
    title: "Visage mystérieux 8",
    src: "https://picsum.photos/seed/traveler8/900/600",
    alt: "Personnage mystérieux 8",
    isBoss: false,
    hint: "Ce n'est probablement pas un boss.",
  },
  {
    id: 9,
    title: "Visage mystérieux 9",
    src: "https://picsum.photos/seed/boss9/900/600",
    alt: "Personnage mystérieux 9",
    isBoss: true,
    hint: "Son apparence inspire le respect.",
  },
  {
    id: 10,
    title: "Visage mystérieux 10",
    src: "https://picsum.photos/seed/hero10/900/600",
    alt: "Personnage mystérieux 10",
    isBoss: false,
    hint: "Il a l'air plutôt sympathique.",
  },
];

export default images;
